name: Build Shikimori CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build CSS
        run: |
          mkdir -p dist
          cat \
            src/variables.css \
            src/fonts.css \
            src/glitch.css \
            src/profile.css \
            > dist/main.css

      - name: Commit built CSS
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: update dist/main.css"
